#!/usr/bin/env node
/**
 * gym-app local stack launcher (cross-platform wrapper around `docker compose -p gym-app`).
 *
 * GYM_PROJECT=<name> runs an isolated copy of the stack (own containers and volumes), e.g. for CI.
 *
 *   node scripts/local/gym.mjs init [--force]     generate .env.local with local-only secrets
 *   node scripts/local/gym.mjs up [profiles...]   start (profiles: mail, stripe, studio)
 *   node scripts/local/gym.mjs down               stop, keep data
 *   node scripts/local/gym.mjs reset              stop and DELETE all data (Postgres, Redis, node_modules volume)
 *   node scripts/local/gym.mjs migrate            apply new files from supabase/migrations
 *   node scripts/local/gym.mjs test-db            run the database (RLS) tests against the running stack
 *   node scripts/local/gym.mjs test-sync          two-browser end-to-end sync test (stack must be up)
 *   node scripts/local/gym.mjs psql [args]        open psql in the running database (as the admin role); extra args go to psql
 *   node scripts/local/gym.mjs seed <email>       add 4 weeks of demo workout days to an existing local account
 *   node scripts/local/gym.mjs ps | logs [service] | restart <service>
 */
import { createHmac, randomBytes } from "node:crypto";
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const ENV_FILE = path.join(ROOT, ".env.local");
const ENV_BACKUP = path.join(ROOT, ".env.local.remote");
const COMPOSE_FILE = path.join(ROOT, "docker", "compose.yaml");
// Overridable so a throwaway stack (CI, rehearsals) never shares containers or volumes with your dev stack.
const PROJECT = process.env.GYM_PROJECT ?? "gym-app";
const MARKER = "# gym-app local stack";
const PROFILES = ["mail", "stripe", "studio"];

const base64url = (input) => Buffer.from(input).toString("base64url");

function signJwt(secret, role) {
  const iat = Math.floor(Date.now() / 1000);
  const header = base64url(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const payload = base64url(JSON.stringify({ iss: "gym-local", role, iat, exp: iat + 10 * 365 * 24 * 3600 }));
  const signature = createHmac("sha256", secret).update(`${header}.${payload}`).digest("base64url");
  return `${header}.${payload}.${signature}`;
}

function isGenerated() {
  return existsSync(ENV_FILE) && readFileSync(ENV_FILE, "utf8").startsWith(MARKER);
}

function init(force) {
  if (isGenerated() && !force) {
    console.log(".env.local is already a gym-app file. Regenerating would change the database password,");
    console.log("which an existing Postgres volume will not pick up. Run `npm run gym:reset` first, then `gym:init -- --force`.");
    return 0;
  }
  if (existsSync(ENV_FILE) && !isGenerated()) {
    if (existsSync(ENV_BACKUP)) {
      console.error(`Refusing to overwrite: ${path.basename(ENV_BACKUP)} already exists. Move it away and retry.`);
      return 1;
    }
    renameSync(ENV_FILE, ENV_BACKUP);
    console.log(`Existing .env.local saved as ${path.basename(ENV_BACKUP)}.`);
  }

  const jwtSecret = randomBytes(32).toString("hex");
  const anon = signJwt(jwtSecret, "anon");
  const service = signJwt(jwtSecret, "service_role");
  const lines = [
    `${MARKER} (generated by \`npm run gym:init\`). Local-only values: never reuse them anywhere real.`,
    "",
    `GYM_POSTGRES_PASSWORD=${randomBytes(24).toString("hex")}`,
    `SUPABASE_JWT_SECRET=${jwtSecret}`,
    `GYM_ANON_KEY=${anon}`,
    `GYM_SERVICE_ROLE_KEY=${service}`,
    "",
    "# Browser (Vite). Auth and data go through the local gateway; /api calls are proxied to the API container.",
    "VITE_SUPABASE_URL=http://localhost:54321",
    `VITE_SUPABASE_ANON_KEY=${anon}`,
    "VITE_SUPABASE_REDIRECT_URL=http://localhost:5180",
    "",
    "# API container (/api handlers). Hostnames are compose service names.",
    "SUPABASE_URL=http://gateway:8000",
    `SUPABASE_ANON_KEY=${anon}`,
    `SUPABASE_SERVICE_ROLE_KEY=${service}`,
    `SUPABASE_JWT_SECRET=${jwtSecret}`,
    "KV_REST_API_URL=http://kv-rest:80",
    `KV_REST_API_TOKEN=${randomBytes(16).toString("hex")}`,
    "",
    "# Stripe: only reachable while the `stripe` profile (stripe-mock) is running.",
    "STRIPE_SECRET_KEY=sk_test_local_mock",
    "STRIPE_WEBHOOK_SECRET=whsec_gym_local",
    "STRIPE_PRO_PRICE_ID=price_gym_local",
    "STRIPE_API_BASE=http://stripe:12111/v1",
    "",
    "# Set to false (and start the `mail` profile) to test email confirmation; true skips the inbox.",
    "GYM_AUTOCONFIRM=true",
    "",
  ];
  writeFileSync(ENV_FILE, lines.join("\n"));
  console.log("Wrote .env.local with fresh local-only secrets. Next: npm run gym:up");
  return 0;
}

function compose(args, profiles = [], input) {
  const full = [
    "compose",
    "--env-file", ENV_FILE,
    "-f", COMPOSE_FILE,
    "-p", PROJECT,
    ...profiles.flatMap((p) => ["--profile", p]),
    ...args,
  ];
  const options = input === undefined ? { stdio: "inherit", cwd: ROOT } : { stdio: ["pipe", "inherit", "inherit"], cwd: ROOT, input };
  return spawnSync("docker", full, options).status ?? 1;
}

function requireEnv() {
  if (isGenerated()) return true;
  console.error("No gym-app .env.local yet. Run: npm run gym:init");
  return false;
}

const [command = "help", ...rest] = process.argv.slice(2);
let code = 0;

switch (command) {
  case "init":
    code = init(rest.includes("--force"));
    break;
  case "up": {
    if (!requireEnv()) { code = 1; break; }
    const unknown = rest.filter((p) => !PROFILES.includes(p));
    if (unknown.length > 0) {
      console.error(`Unknown profile(s): ${unknown.join(", ")}. Available: ${PROFILES.join(", ")}`);
      code = 1;
      break;
    }
    code = compose(["up", "-d"], rest);
    if (code === 0) {
      console.log("\n  App        http://localhost:5180      API   http://localhost:3010");
      console.log("  Gateway    http://localhost:54321     DB    postgresql://postgres@localhost:54322/postgres");
      if (rest.includes("mail")) console.log("  Mail UI    http://localhost:8026");
      if (rest.includes("studio")) console.log("  Studio     http://localhost:54323");
      console.log("  Stop with: npm run gym:down\n");
    }
    break;
  }
  case "down":
    if (!requireEnv()) { code = 1; break; }
    code = compose(["down", "--remove-orphans"], PROFILES);
    break;
  case "reset":
    if (!requireEnv()) { code = 1; break; }
    code = compose(["down", "--remove-orphans", "--volumes"], PROFILES);
    break;
  case "migrate":
    if (!requireEnv()) { code = 1; break; }
    code = compose(["run", "--rm", "--no-deps", "migrate"]);
    break;
  case "test-db": {
    if (!requireEnv()) { code = 1; break; }
    console.log("== SQL tests (RLS, constraints, triggers) ==");
    code = compose(["exec", "-T", "db", "psql", "-U", "supabase_admin", "-d", "postgres", "-v", "ON_ERROR_STOP=1", "-q", "-o", "/dev/null", "-f", "/tests/rls.test.sql"]);
    if (code !== 0) break;
    console.log("\n== API smoke (real JWTs through gateway -> PostgREST) ==");
    code = spawnSync(process.execPath, [path.join(ROOT, "scripts", "local", "db-smoke.mjs")], { stdio: "inherit", cwd: ROOT }).status ?? 1;
    break;
  }
  case "test-sync":
    if (!requireEnv()) { code = 1; break; }
    code = spawnSync(process.execPath, [path.join(ROOT, "scripts", "local", "e2e-sync.mjs")], { stdio: "inherit", cwd: ROOT }).status ?? 1;
    break;
  case "psql":
    if (!requireEnv()) { code = 1; break; }
    code = compose(["exec", "db", "psql", "-U", "supabase_admin", "-d", "postgres", ...rest]);
    break;
  case "seed": {
    if (!requireEnv()) { code = 1; break; }
    const email = rest[0];
    if (!email || !email.includes("@")) {
      console.error("Usage: npm run gym:seed -- <email of an existing local account>");
      code = 1;
      break;
    }
    const sql = readFileSync(path.join(ROOT, "supabase", "seed", "demo_days.sql"), "utf8");
    code = compose(["exec", "-T", "db", "psql", "-U", "supabase_admin", "-d", "postgres", "-v", `email=${email}`], [], sql);
    break;
  }
  case "ps":
    if (!requireEnv()) { code = 1; break; }
    code = compose(["ps", "--all"], PROFILES);
    break;
  case "logs":
    if (!requireEnv()) { code = 1; break; }
    code = compose(["logs", "--tail", "100", "-f", ...rest], PROFILES);
    break;
  case "restart":
    if (!requireEnv()) { code = 1; break; }
    code = compose(["restart", ...rest], PROFILES);
    break;
  default:
    console.log("Usage: npm run gym:<init|up|down|reset|psql|seed|ps|logs|restart> [-- args]");
    console.log(`Profiles for up: ${PROFILES.join(", ")}  (e.g. npm run gym:up -- mail studio)`);
}

process.exit(code);
