import 'dart:convert';
import 'dart:io';

import 'package:daily_grind/domain/models.dart';
import 'package:daily_grind/sync/content_hash.dart';
import 'package:daily_grind/sync/day_hash.dart';
import 'package:flutter_test/flutter_test.dart';

/// Golden fixtures are generated by the web app (contract/contentHash.contract.test.ts).
void main() {
  final fixture = jsonDecode(File('../contract/contentHash.fixtures.json').readAsStringSync()) as Map<String, dynamic>;

  test('hashString matches the web app', () {
    for (final c in fixture['hashString'] as List) {
      expect(hashString(c['input'] as String), c['hash'], reason: 'input: ${jsonEncode(c['input'])}');
    }
  });

  for (final c in fixture['days'] as List) {
    test('day "${c['name']}" serialises and hashes like the web app', () {
      final day = DayData.fromJson((c['day'] as Map).cast<String, Object?>());
      expect(stableSerialize(day.toJson()), c['serialized']);
      expect(dayContentHash(day), c['hash']);
    });
  }
}
