import 'dart:convert';
import 'dart:io';

import 'package:daily_grind/domain/dates.dart';
import 'package:daily_grind/domain/plan_text.dart' as plan_text;
import 'package:daily_grind/domain/models.dart';
import 'package:daily_grind/domain/session_types.dart';
import 'package:daily_grind/domain/templates.dart';
import 'package:daily_grind/domain/workout_transitions.dart';
import 'package:daily_grind/domain/rules.dart';
import 'package:daily_grind/sync/sync_status.dart';
import 'package:flutter_test/flutter_test.dart';

/// Replays contract/dashboard.fixtures.json, generated by the web app: the wording and ordering a user sees and the
/// day transitions must be the same on both clients.
typedef M = Map<String, dynamic>;

Templates templatesOf(Object? raw) => {
      for (final e in (raw as M).entries) e.key: TemplateData.fromJson((e.value as Map).cast<String, Object?>()),
    };

Object? norm(Object? v) => jsonDecode(jsonEncode(v));

DayData dayWith(List<bool> done) {
  WorkoutItem item(String id, bool d) => WorkoutItem(id: id, text: id, done: d);
  return DayData(
    date: '2026-10-01',
    sessionType: 'gym',
    warmup: [for (var i = 0; i < done.length && i < 2; i++) item('w$i', done[i])],
    main: [for (var i = 2; i < done.length; i++) item('m${i - 2}', done[i])],
    warmupNotes: 'n',
    mainNotes: 'm',
    warmupTimerMs: 5000,
    mainTimerMs: 7000,
    weight: '80',
    checkNotes: 'c',
  );
}

Object? resultJson(SessionTypeResult r) => norm({
      'status': r.status.name,
      'message': r.message,
      if (r.sessionType != null) 'sessionType': r.sessionType,
      if (r.oldSessionType != null) 'oldSessionType': r.oldSessionType,
      if (r.newSessionType != null) 'newSessionType': r.newSessionType,
      if (r.templates != null) 'templates': templatesToJson(r.templates!),
    });

void main() {
  final f = jsonDecode(File('../contract/dashboard.fixtures.json').readAsStringSync()) as M;

  test('timer text', () {
    for (final c in f['formatTimer'] as List) {
      expect(formatTimer(c['ms'] as int), c['text'], reason: '${c['ms']}ms');
    }
  });

  test('progress rounds like the web app', () {
    for (final c in f['progress'] as List) {
      final done = (c['done'] as List).cast<bool>();
      expect(dayProgress(dayWith(done)), c['percent'], reason: '$done');
    }
  });

  group('session types', () {
    test('labels', () {
      for (final c in f['sessionLabels'] as List) {
        expect(getSessionLabel(c['id'] as String), c['label'], reason: 'id: ${c['id']}');
      }
    });

    test('option lists: built-ins first in fixed order, custom ones in locale order, with focus and source', () {
      for (final c in f['sessionOptions'] as List) {
        final options = getSessionOptions(templatesOf(c['templates']));
        expect(norm([for (final o in options) o.toJson()]), c['options'], reason: c['name'] as String);
      }
    });

    test('ids from what the user typed', () {
      for (final c in f['normalizeId'] as List) {
        expect(normalizeSessionTypeId(c['label'] as String), c['id'], reason: 'label: ${c['label']}');
      }
    });

    test('create, delete and rename: same results and same wording', () {
      final base = templatesOf((f['sessionOptions'] as List).firstWhere((c) => c['name'] == 'withMeta')['templates']);
      for (final c in f['createSession'] as List) {
        expect(resultJson(createSessionType(base, c['label'] as String)), c['result'], reason: 'create ${c['label']}');
      }
      for (final c in f['deleteSession'] as List) {
        expect(resultJson(deleteSessionType(base, c['type'] as String)), c['result'], reason: 'delete ${c['type']}');
      }
      for (final c in f['renameSession'] as List) {
        expect(resultJson(renameSessionType(base, c['type'] as String, c['label'] as String)), c['result'],
            reason: 'rename ${c['type']} to ${c['label']}');
      }
    });
  });

  test('day transitions', () {
    final t = f['transitions'] as M;
    final templates = templatesOf(t['templates']);
    final day = DayData.fromJson((t['day'] as Map).cast<String, Object?>());
    String id() => 'i';
    Object? j(DayData d) => norm(d.toJson());

    expect(j(toggleItemInSection(day, WorkoutSection.main, 'm0', false)), t['toggle']);
    expect(j(toggleItemInSection(day, WorkoutSection.main, 'zzz', true)), t['toggleMissing']);
    expect(j(deleteItemInSection(day, WorkoutSection.warmup, 'w1')), t['deleteItem']);
    expect(j(resetSectionsFromTemplate('2026-10-02', 'yoga', day, templates: templates, idGen: id)), t['reset']);
    expect(j(resetSectionsFromTemplate('2026-10-02', 'mystery', day, templates: templates, idGen: id)), t['resetUnknown']);
    expect(j(clearDayKeepingSession('2026-10-02', 'yoga', templates: templates, idGen: id)), t['clear']);
    expect(j(createEmptyDay('2026-10-02', 'tennis', idGen: id)), t['emptyDefault']);
  });

  group('sync status', () {
    test('every golden case: kind, label and the sentence shown', () {
      for (final c in f['syncStatus'] as List) {
        final i = c['input'] as M;
        final a = i['allowance'] as M?;
        final s = deriveSyncStatus(
          isSyncing: i['isSyncing'] as bool,
          isOnline: i['isOnline'] as bool,
          conflictCount: i['conflictCount'] as int,
          lastError: i['lastError'] as String?,
          lastSyncedAt: i['lastSyncedAt'] as String?,
          allowance: a == null ? null : (nextAvailableAt: a['nextAvailableAt'] as String?),
          now: DateTime.fromMillisecondsSinceEpoch(i['now'] as int, isUtc: true),
        );
        final want = c['status'] as M;
        expect([s.kind.name, s.label, s.detail], [want['kind'], want['label'], want['detail']], reason: jsonEncode(i));
      }
    });

    test('the next-sync date is written the way en-GB does, including "Sept"', () {
      for (final c in f['nextSync'] as List) {
        expect(formatNextSync(c['iso'] as String), c['text']);
      }
    });
  });

  test('plan wording matches the web app', () {
    final t = f['planText'] as M;
    expect(plan_text.freePlanSummary, t['freeSummary']);
    expect(plan_text.whenProEnds, t['whenProEnds']);
    expect(plan_text.cancelNote, t['cancelNote']);
  });

  group('date keys', () {
    test('round trip and shifting across month, year and leap boundaries', () {
      expect(toLocalDateKey(fromLocalDateKey('2026-10-03')), '2026-10-03');
      expect(shiftDateKey('2026-10-01', -1), '2026-09-30');
      expect(shiftDateKey('2026-01-01', -1), '2025-12-31');
      expect(shiftDateKey('2028-03-01', -1), '2028-02-29');
      expect(shiftDateKey('2026-12-31', 1), '2027-01-01');
      expect(shiftDateKey('2026-10-03', 0), '2026-10-03');
    });

    test('a key that is not numbers falls back to today, like the web app', () {
      final now = DateTime(2026, 10, 3, 9);
      expect(fromLocalDateKey('not-a-date', now), now);
      expect(fromLocalDateKey('2026-10', now), now);
    });

    test('Monday-first weekday index', () {
      expect(mondayIndex(DateTime(2026, 10, 5)), 0); // Monday
      expect(mondayIndex(DateTime(2026, 10, 11)), 6); // Sunday
    });
  });
}
