import 'dart:convert';
import 'dart:io';

import 'package:daily_grind/domain/exercise_library.dart';
import 'package:daily_grind/domain/models.dart';
import 'package:daily_grind/domain/template_rules.dart';
import 'package:daily_grind/domain/video_url.dart';
import 'package:flutter_test/flutter_test.dart';

/// Replays contract/editors.fixtures.json, generated by the web app.
typedef M = Map<String, dynamic>;

void main() {
  final f = jsonDecode(File('../contract/editors.fixtures.json').readAsStringSync()) as M;

  test('video links: the same ones are accepted', () {
    for (final c in f['youtube'] as List) {
      expect(isValidYouTubeUrl(c['url'] as String), c['valid'], reason: jsonEncode(c['url']));
    }
  });

  test('row validation: same problems, same words, same order', () {
    for (final c in f['rows'] as List) {
      final rows = [
        for (final r in c['rows'] as List) (text: (r as M)['text'] as String, target: r['target'] as String?),
      ];
      final got = [for (final e in validateTemplateRows(rows)) {'rowIndex': e.rowIndex, 'field': e.field, 'message': e.message}];
      expect(got, c['errors'], reason: jsonEncode(c['rows']));
    }
  });

  test('exercise library: deduplicated, newest spelling wins, sorted like the web app', () {
    for (final c in f['library'] as List) {
      final days = {
        for (final e in (c['days'] as M).entries) e.key: DayData.fromJson((e.value as Map).cast<String, Object?>()),
      };
      final got = [
        for (final e in buildExerciseLibrary(days)) {'text': e.text, if (e.target != null) 'target': e.target},
      ];
      expect(got, c['entries'], reason: c['name'] as String);
    }
  });

  group('suggestions while typing', () {
    const library = [
      ExerciseLibraryEntry(text: 'Bench press', target: '3x8'),
      ExerciseLibraryEntry(text: 'Incline bench press'),
      ExerciseLibraryEntry(text: 'Bench'),
      ExerciseLibraryEntry(text: 'Dumbbell bench row', target: '3x10'),
      ExerciseLibraryEntry(text: 'Squat'),
    ];

    test('matches anywhere, never the exact name, starts-with first then alphabetical', () {
      expect(suggestExercises('bench', library).map((e) => e.text), ['Bench press', 'Dumbbell bench row', 'Incline bench press']);
    });

    test('case and surrounding spaces do not matter; nothing typed or an empty library suggests nothing', () {
      expect(suggestExercises('  SQU ', library).map((e) => e.text), ['Squat']);
      expect(suggestExercises('   ', library), isEmpty);
      expect(suggestExercises('bench', const []), isEmpty);
      expect(suggestExercises('zzz', library), isEmpty);
    });

    test('at most eight', () {
      final many = [for (var i = 0; i < 20; i++) ExerciseLibraryEntry(text: 'Curl $i')];
      expect(suggestExercises('curl', many), hasLength(8));
    });

    test('carries the target along so choosing a suggestion can fill it in', () {
      expect(suggestExercises('dumbbell', library).single.target, '3x10');
    });
  });
}
