import 'dart:convert';
import 'dart:io';

import 'package:daily_grind/domain/rules.dart';
import 'package:daily_grind/domain/templates.dart';
import 'package:daily_grind/sync/content_hash.dart';
import 'package:daily_grind/sync/day_hash.dart';
import 'package:flutter_test/flutter_test.dart';

/// Golden cases generated by the web app (contract/sanitize.contract.test.ts). Masking mirrors the web side:
/// generated ids (`/^[0-9a-z]{1,7}$/`) become `"<gen>"`, and an `updatedAt` the input did not carry becomes `"<now>"`.
typedef M = Map<String, dynamic>;

final _genId = RegExp(r'^[0-9a-z]{1,7}$');

Object? maskIds(Object? v) {
  if (v is List) return [for (final e in v) maskIds(e)];
  if (v is Map) {
    return {
      for (final e in v.entries)
        e.key: e.key == 'id' && e.value is String && _genId.hasMatch(e.value as String) ? '<gen>' : maskIds(e.value),
    };
  }
  return v;
}

/// Through JSON, as the web side does, so numbers and key sets compare like for like.
Object? norm(Object? v) => maskIds(jsonDecode(jsonEncode(v)));

Map<String, Object?> envelope(Object snapshot, Object? raw) {
  // ignore: avoid_dynamic_calls
  final s = snapshot as dynamic;
  final data = s.data;
  final supplied = raw is Map && raw['updatedAt'] is String ? raw['updatedAt'] : null;
  return {
    'version': s.version,
    'updatedAt': s.updatedAt == supplied ? s.updatedAt : '<now>',
    'data': data is Map
        ? {
            for (final e in data.entries)
              e.key: (e.value as dynamic).toJson(),
          }
        : [for (final p in data as List) (p as dynamic).toJson()],
  };
}

void main() {
  final f = jsonDecode(File('../contract/sanitize.fixtures.json').readAsStringSync()) as M;

  group('sanitizeDayData', () {
    for (final c in f['sanitizeDay'] as List) {
      test(c['name'] as String, () {
        final day = sanitizeDayData(c['raw'], c['date'] as String);
        expect(norm(day.toJson()), c['expected']);
      });
    }
  });

  group('sanitizeTemplates', () {
    for (final c in f['sanitizeTemplates'] as List) {
      test(c['name'] as String, () {
        expect(norm(templatesToJson(sanitizeTemplates(c['raw']))), c['expected']);
      });
    }
  });

  // The web hashes the sanitised objects, which carry explicit undefined keys. See the web test for why.
  group('hash form (explicit undefined keys)', () {
    final hashes = f['hashes'] as M;

    for (final c in hashes['days'] as List) {
      test('day: ${c['name']}', () {
        final day = sanitizeDayData(c['raw'], c['date'] as String, idGen: () => 'i');
        expect(stableSerialize(day.toHashJson()), c['serialized']);
        expect(dayContentHash(day), c['hash']);
      });
    }

    for (final c in hashes['templates'] as List) {
      test('templates: ${c['name']}', () {
        final sanitized = sanitizeTemplates(c['raw'], idGen: () => 'i');
        final items = c['items'] as M;
        expect(sanitized.keys, items.keys);
        for (final e in sanitized.entries) {
          expect(stableSerialize(e.value.toHashJson()), items[e.key]['serialized'], reason: e.key);
          expect(entityHash(e.value.toHashJson()), items[e.key]['hash'], reason: e.key);
        }
      });
    }

    test('the hash form survives the collection round trip the merge puts templates through', () {
      final sanitized = sanitizeTemplates({
        'yoga': {
          'label': 'Flow',
          'warmup': [{'id': 'ID-1', 'text': 'Cat-cow'}],
          'main': <Object?>[],
        },
      });
      final before = entityHash(sanitized['yoga']!.toHashJson());
      final viaJson = TemplateData.fromJson(sanitized['yoga']!.toHashJson());
      expect(entityHash(viaJson.toHashJson()), before);
      // And the plain stored form is not the hashed form: that difference is the whole point.
      expect(entityHash(sanitized['yoga']!.toJson()), isNot(before));
    });
  });

  group('snapshot migrations', () {
    test('workout (${(f['migrateWorkout'] as List).length} cases)', () {
      for (final c in f['migrateWorkout'] as List) {
        expect(norm(envelope(migrateRawWorkoutSnapshot(c['raw']), c['raw'])), c['expected'], reason: jsonEncode(c['raw']));
      }
    });
    test('templates (${(f['migrateTemplates'] as List).length} cases)', () {
      for (final c in f['migrateTemplates'] as List) {
        expect(norm(envelope(migrateRawTemplateSnapshot(c['raw']), c['raw'])), c['expected'], reason: jsonEncode(c['raw']));
      }
    });
    test('plans (${(f['migratePlans'] as List).length} cases)', () {
      for (final c in f['migratePlans'] as List) {
        expect(norm(envelope(migrateRawPlansSnapshot(c['raw']), c['raw'])), c['expected'], reason: jsonEncode(c['raw']));
      }
    });
  });
}
