import 'dart:convert';
import 'dart:io';

import 'package:daily_grind/domain/models.dart';
import 'package:daily_grind/sync/sync_merge.dart';
import 'package:flutter_test/flutter_test.dart';

/// Golden scenarios generated by the web app (contract/syncMerge.contract.test.ts). Every case must match.
typedef M = Map<String, dynamic>;

Map<String, DayData> days(Object? v) => {
      for (final e in (v as M).entries) e.key: DayData.fromJson((e.value as Map).cast<String, Object?>()),
    };
Json dayJson(Map<String, DayData> d) => {for (final e in d.entries) e.key: e.value.toJson()};
Map<String, String> strMap(Object? v) => (v as Map).cast<String, String>();
Collection coll(Object? v) {
  if (v == null) return Collection.empty;
  final m = v as M;
  return Collection((m['keys'] as List).cast<String>(), (m['items'] as Map).cast<String, Object?>());
}

ConflictResolution? res(Object? v) => v == null ? null : ConflictResolution.values.byName(v as String);

void main() {
  final f = jsonDecode(File('../contract/syncMerge.fixtures.json').readAsStringSync()) as M;

  group('mergeWorkoutDays', () {
    final cases = f['workoutMerge'] as List;
    test('all ${cases.length} scenarios match the web app', () {
      for (final c in cases) {
        final i = c['input'] as M;
        final r = mergeWorkoutDays(days(i['local']), days(i['cloud']), strMap(i['baseDays']), res(i['resolution']));
        final exp = c['expected'] as M;
        expect(dayJson(r.merged), exp['merged'], reason: jsonEncode(i));
        expect(r.conflictKeys, exp['conflictKeys'], reason: jsonEncode(i));
      }
    });
  });

  group('mergeCollection', () {
    final cases = f['collectionMerge'] as List;
    test('all ${cases.length} scenarios match the web app', () {
      for (final c in cases) {
        final i = c['input'] as M;
        final o = i['options'] as M;
        final r = mergeCollection(
          coll(i['local']),
          coll(i['cloud']),
          strMap(i['base']),
          resolution: res(o['resolution']),
          localWinsConflicts: o['localWinsConflicts'] as bool,
        );
        final exp = c['expected'] as M;
        expect(r.merged.toJson(), exp['merged'], reason: jsonEncode(i));
        expect(r.conflictKeys, exp['conflictKeys'], reason: jsonEncode(i));
      }
    });
  });

  group('reconcileDeletions', () {
    final cases = f['deletions'] as List;
    test('all ${cases.length} scenarios match the web app', () {
      for (final c in cases) {
        final i = c['input'] as M;
        final r = reconcileDeletions(
          days(i['localData']),
          strMap(i['localDeleted']),
          days(i['cloudData']),
          strMap(i['cloudDeleted']),
        );
        final exp = c['expected'] as M;
        expect(dayJson(r.local), exp['local'], reason: jsonEncode(i));
        expect(dayJson(r.cloud), exp['cloud'], reason: jsonEncode(i));
        expect(r.deleteInCloud, exp['deleteInCloud'], reason: jsonEncode(i));
        expect(r.deleteLocally, exp['deleteLocally'], reason: jsonEncode(i));
      }
    });
  });

  group('sync base helpers', () {
    final b = f['base'] as M;

    test('agreedBase', () {
      for (final c in b['agreedBase'] as List) {
        expect(agreedBase(coll(c['merged']), c['localAfter'] == null ? null : coll(c['localAfter']), strMap(c['previous'])),
            c['expected']);
      }
    });

    test('agreedDaysBase', () {
      for (final c in b['agreedDaysBase'] as List) {
        expect(agreedDaysBase(days(c['merged']), c['localAfter'] == null ? null : days(c['localAfter']), strMap(c['previous'])), c['expected']);
      }
    });

    test('collectionHashes', () {
      for (final c in b['collectionHashes'] as List) {
        expect(collectionHashes(c['collection'] == null ? null : coll(c['collection'])), c['expected']);
      }
    });

    test('baseDaysFrom', () {
      for (final c in b['baseDaysFrom'] as List) {
        expect(baseDaysFrom(days(c['days'])), c['expected']);
      }
    });

    test('baseAfterPartialWrite', () {
      for (final c in b['baseAfterPartialWrite'] as List) {
        expect(baseAfterPartialWrite(strMap(c['previous']), strMap(c['cloudHashes']), strMap(c['localHashes'])),
            c['expected']);
      }
    });
  });

  test('historyCutoff matches the web app across month, year and leap boundaries', () {
    for (final c in f['historyCutoff'] as List) {
      expect(historyCutoff(c['days'] as int, DateTime.parse(c['now'] as String)), c['expected'], reason: jsonEncode(c));
    }
  });

  test('keepRecent drops days older than the cutoff', () {
    expect(keepRecent({'2026-09-30': 1, '2026-10-01': 2, '2026-10-05': 3}, '2026-10-01'), {'2026-10-01': 2, '2026-10-05': 3});
  });
}
